=== officina/learning-deck-lambda/schemas/userstatus_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "world": {
      "type": "object",
      "properties": {
        "status": {
          "type": "object",
          "properties": {
            "casa": {
              "type": "integer"
            },
            "mobilita": {
              "type": "integer"
            },
            "vita": {
              "type": "integer"
            },
            "tempo": {
              "type": "integer"
            }
          },
          "required": [
            "casa",
            "mobilita",
            "vita",
            "tempo"
          ]
        },
        "points": {
          "type": "object",
          "properties": {
            "total": {
              "type": "integer"
            },
            "available": {
              "type": "integer"
            },
            "upgrade": {
              "type": "object",
              "properties": {
                "casa": {
                  "type": "integer"
                },
                "mobilita": {
                  "type": "integer"
                },
                "vita": {
                  "type": "integer"
                },
                "tempo": {
                  "type": "integer"
                }
              },
              "required": [
                "casa",
                "mobilita",
                "vita",
                "tempo"
              ]
            }
          },
          "required": [
            "total",
            "available",
            "upgrade"
          ]
        }
      },
      "required": [
        "status",
        "points"
      ]
    },
    "challenges": {
      "type": "object",
      "properties": {
        "available": {
          "type": "integer"
        },
        "completed": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        }
      },
      "required": [
        "available",
        "completed"
      ]
    },
    "progress": {
      "type": "object",
      "properties": {
        "ranking": {
          "type": "number"
        },
        "params": {
          "type": "object",
          "properties": {
            "sicurezza": {
              "type": "number"
            },
            "salute": {
              "type": "number"
            },
            "sostenibilita": {
              "type": "number"
            },
            "risparmio": {
              "type": "number"
            }
          },
          "required": [
            "sicurezza",
            "salute",
            "sostenibilita",
            "risparmio"
          ]
        }
      },
      "required": [
        "ranking",
        "params"
      ]
    },
    "timestamp": {
      "type": "integer"
    }
  },
  "required": [
    "world",
    "challenges",
    "progress",
    "timestamp"
  ]
}

=== officina/learning-deck-lambda/tests/get_user_response.json
{
    "world": {
        "status": {
            "casa": 0, 
            "mobilita": 0,
            "vita": 0,
            "tempo": 0
        },
        "points": {
            "total": 20,
            "available": 10,
            "upgrade": {
                "casa": 10,
                "mobilita": 10,
                "vita": 10,
                "tempo": 10
            }
        }
    },
    "challenges": {
        "available": 52,
        "completed": [
          "S01_C01_C00001"
        ]
    },
    "progress": {
        "ranking": 0.25,
        "params": {
            "sicurezza": 0.67,
            "salute": 0.67,
            "sostenibilita": 0,
            "risparmio": 0.67
        }
    },
    "timestamp":1528806484751
}
